# Generated by Django 4.2.13 on 2024-07-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_portifolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portifolio',
            new_name='portfolio',
        ),
    ]
