# Generated by Django 4.2.13 on 2024-07-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_portifolio_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='des',
            new_name='desc',
        ),
    ]
