# Generated by Django 4.2.13 on 2024-08-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='name',
        ),
    ]
